### ISSUE TITLE
Schöne Statistik aus dem Speedtest generieren

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#257]
Daten zur aktuellen Geschwindigkeit im Lab sind jetzt unter `http://hannswurscht.openlab.lan/speedtest.yaml` verfügbar, generiert [von diesem Skript](https://github.com/openlab-aux/vuizvui/blob/master/modules/user/openlab/speedtest.py).

Schauen so aus:

```yaml
---
version: 0.2
date: 2017-07-08 23:57:39.440277
ping-v4: true
ping-v6: false
dns: true
download_speed: 923104
---
version: 0.2
date: 2017-07-09 00:00:48.535216
ping-v4: true
ping-v6: false
dns: true
download_speed: 3415513
```

* [vuizvui speedtest Modul](https://github.com/openlab-aux/vuizvui/blob/master/modules/user/openlab/speedtest.nix)
* [config auf hannswurscht](https://github.com/openlab-aux/vuizvui/blob/master/machines/labnet/labtops.nix#L50-L61)

Man sollte das zu einer schönen Grafik umwandeln oder so. cc @richi235
